### ISSUE TITLE
Closing tag visible in Transaction History Instructions

### ISSUE THREAD

**Issue by brendankirby** [JakeDarling/swen-344-project#115]
![screen shot 2015-12-06 at 9 36 48 am](https://cloud.githubusercontent.com/assets/3248787/11613828/18fbd5cc-9bfd-11e5-954c-b2895eac2b33.png)

**Comment by xdmds** [comment]
fixed in commit c793248 PR #116

**Comment by brendankirby** [comment]
Fix verified.
