### ISSUE TITLE
Modal shows Add Event title instead of Edit Event

### ISSUE THREAD

**Issue by brendankirby** [JakeDarling/swen-344-project#119]
If I click an event the first time it shows "Edit Event", but if I add an event, close the add modal and click an event, it shows the "Add Event" title instead of "Edit Event". It still imports the data right. 

![screen shot 2015-12-06 at 4 37 39 pm](https://cloud.githubusercontent.com/assets/3248787/11615777/d0227fdc-9c37-11e5-86be-725b3c1b8e60.png)

**Comment by TheEibwen** [comment]
Checking into this now.

**Comment by TheEibwen** [comment]
Fixed in pull #126.
