### ISSUE TITLE
Posts show incorrect dates

### ISSUE THREAD

**Issue by TheEibwen** [JakeDarling/swen-344-project#132]
![image](https://cloud.githubusercontent.com/assets/6843446/11616827/1ff39210-9c53-11e5-9b43-390f73818845.png)

**Comment by brendankirby** [comment]
Is it just an edge case or is it like that for a lot of them?

**Comment by TheEibwen** [comment]
A lot of them for instance:

Epic:
![image](https://cloud.githubusercontent.com/assets/6843446/11616861/e70e5d9e-9c53-11e5-8752-690ef91b374e.png)

Facebook:
![image](https://cloud.githubusercontent.com/assets/6843446/11616863/ee1d4e56-9c53-11e5-8d6a-a5d1016b0381.png)

**Comment by brendankirby** [comment]
Ok I'll take a look, not sure if I'll be able to make a fix in time. Probably low priority at this point.
